backend:
  name: github
  repo: "FatemehAhmadnezhad/Portfolio"
  branch: master # اطمینان حاصل کنید که این نام شاخه اصلی شماست
  auth_type: github
  app_id: "Ov23liEmdIM9fK8gTMBt" # Client ID شما

# ... (بخش backend شما در اینجا) ...

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

media_library: # این بخش برای رفع خطای قبلی media_library اضافه شده بود
  name: git   # فقط نام کتابخانه را مشخص می‌کنیم

collections:
  # ... (بقیه تنظیمات collections شما در اینجا) ...
collections:
  - name: "posts" # نام داخلی برای این مجموعه
    label: "نمونه کارها / پست‌ها" # برچسبی که در داشبورد نمایش داده می‌شود
    folder: "_posts" # پوشه‌ای که فایل‌های Markdown این مجموعه در آن ذخیره می‌شوند
    create: true # اجازه ایجاد آیتم‌های جدید
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # فرمت نام فایل برای آیتم‌های جدید
    fields: # فیلدهایی که برای هر آیتم در این مجموعه تعریف می‌شوند
      - {label: "عنوان", name: "title", widget: "string"}
      - {label: "تاریخ انتشار", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "چیدمان", name: "layout", widget: "hidden", default: "single"}
      - label: "دسته‌بندی برای پوشه تصاویر"
        name: "image_folder_category"
        widget: "string"
        hint: "نام انگلیسی و با حروف کوچک برای پوشه تصاویر (مثلاً: infographics, posters, logos). از خط تیره (-) بجای فاصله استفاده کنید."
        pattern: ['^[a-z0-9-]+$', "فقط حروف کوچک انگلیسی، اعداد و خط تیره مجاز است."]
      - label: "دسته‌بندی‌ها (برای نمایش)"
        name: "categories"
        widget: "list"
        required: false
        hint: "دسته‌بندی‌های نمایشی پست. هر کدام در یک خط جدید یا با کاما جدا شوند."
      - label: "هدر پست"
        name: "header"
        widget: "object"
        fields:
          - label: "تصویر تیزر (برای لیست‌ها)"
            name: "teaser"
            widget: "image"
            # مسیرهای آپلود و نمایش برای این فیلد خاص:
            media_folder: "assets/images/portfolio/{{fields.image_folder_category}}"
            public_folder: "/assets/images/portfolio/{{fields.image_folder_category}}"
            required: false
            hint: "ابتدا فیلد 'دسته‌بندی برای پوشه تصاویر' را پر کرده و پست را (حتی به صورت پیش‌نویس) یکبار ذخیره کنید، سپس تصویر را آپلود یا انتخاب نمایید."
          - label: "تصویر اصلی (برای صفحه پست)"
            name: "image"
            widget: "image"
            # مسیرهای آپلود و نمایش برای این فیلد خاص:
            media_folder: "assets/images/portfolio/{{fields.image_folder_category}}"
            public_folder: "/assets/images/portfolio/{{fields.image_folder_category}}"
            required: false
            hint: "ابتدا فیلد 'دسته‌بندی برای پوشه تصاویر' را پر کرده و پست را (حتی به صورت پیش‌نویس) یکبار ذخیره کنید، سپس تصویر را آپلود یا انتخاب نمایید."
          - {label: "کپشن تصویر اصلی (اختیاری)", name: "caption", widget: "string", required: false}
      - {label: "خلاصه (اختیاری)", name: "excerpt", widget: "text", required: false}
      - {label: "محتوای اصلی", name: "body", widget: "markdown"}
