# محتوای اولیه برای admin/config.yml - این را در قدم‌های بعدی تکمیل می‌کنیم
backend:
  name: github
  repo: "FatemehAhmadnezhad/Portfolio" # نام کاربری و مخزن شما
  branch: master # یا main، مطمئن شوید نام شاخه اصلی شما صحیح است
  auth_type: github # <<< اینجا را به 'github' تغییر دهید
  app_id: Ov23liEmdIM9fK8gTMBt # <<< Client ID که از گیت‌هاب کپی کردید را اینجا قرار دهید
  base_url: https://api.github.com # (اختیاری، اما برای وضوح خوب است) آدرس API گیت‌هاب
  auth_endpoint: oauth/authorize # (اختیاری، اما برای وضوح خوب است) نقطه پایانی احراز هویت گیت‌هاب
  # site_domain دیگر برای این روش لازم نیست و می‌توانید آن را حذف کنید یا کامنت نگه دارید.

media_folder: "assets/images/uploads" # مسیری که تصاویر آپلود شده در مخزن ذخیره می‌شوند
public_folder: "/assets/images/uploads" # مسیری که تصاویر از طریق وب‌سایت قابل دسترسی هستند

collections:
  - name: "posts"
    label: "نمونه کارها / پست‌ها"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "عنوان", name: "title", widget: "string"}
      - {label: "تاریخ انتشار", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false} # Corrected line
      - {label: "چیدمان", name: "layout", widget: "hidden", default: "single"}
      - label: "دسته‌بندی اصلی برای پوشه تصاویر" # فیلد جدید
        name: "image_folder_category"
        widget: "string"
        hint: "نام پوشه‌ای که تصاویر این پست در آن آپلود می‌شوند (مثلاً: infographics, posters, logos). لطفاً انگلیسی، با حروف کوچک و بدون فاصله بنویسید. اگر فاصله لازم است از خط تیره (-) استفاده کنید."
        pattern: ['^[a-z0-9-]+$', "لطفاً فقط از حروف کوچک انگلیسی، اعداد و خط تیره استفاده کنید."]
      - label: "سایر دسته‌بندی‌ها (برای نمایش)" # فیلد قبلی دسته‌بندی‌ها
        name: "categories"
        widget: "list"
        required: false
        hint: "دسته‌بندی‌هایی که برای نمایش پست استفاده می‌شوند. هر دسته‌بندی در یک خط جدید یا با کاما جدا شود. می‌توانید دسته‌بندی اصلی بالا را هم اینجا تکرار کنید."
      - label: "هدر پست"
        name: "header"
        widget: "object"
        fields:
          - label: "تصویر تیزر (برای لیست‌ها)"
            name: "teaser"
            widget: "image"
            media_folder: "assets/images/portfolio/{{fields.image_folder_category}}" # استفاده از فیلد جدید
            public_folder: "/assets/images/portfolio/{{fields.image_folder_category}}" # استفاده از فیلد جدید
            required: false
            hint: "تصویر کوچکتر برای نمایش در لیست‌ها. ابتدا این پست را ذخیره کنید، سپس تصویر را در بخش رسانه با توجه به مسیر بالا آپلود و اینجا انتخاب کنید."
          - label: "تصویر اصلی (برای صفحه پست)"
            name: "image"
            widget: "image"
            media_folder: "assets/images/portfolio/{{fields.image_folder_category}}" # استفاده از فیلد جدید
            public_folder: "/assets/images/portfolio/{{fields.image_folder_category}}" # استفاده از فیلد جدید
            required: false
            hint: "تصویر بزرگتر که در بالای صفحه پست نمایش داده می‌شود. ابتدا این پست را ذخیره کنید، سپس تصویر را در بخش رسانه با توجه به مسیر بالا آپلود و اینجا انتخاب کنید."
          - {label: "کپشن تصویر اصلی (اختیاری)", name: "caption", widget: "string", required: false}
      - {label: "خلاصه (اختیاری برای لیست‌ها)", name: "excerpt", widget: "text", required: false}
      - {label: "محتوای اصلی", name: "body", widget: "markdown"}
